/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ArtistProfileInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isArtist"
      | "isVerified"
      | "owner"
      | "profileURI"
      | "profiles"
      | "registerArtist"
      | "renounceOwnership"
      | "setVerified"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArtistRegistered"
      | "ArtistUpdated"
      | "ArtistVerified"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "isArtist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profileURI",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerArtist",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerified",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "isArtist", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profileURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerArtist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ArtistRegisteredEvent {
  export type InputTuple = [artist: AddressLike, name: string, uri: string];
  export type OutputTuple = [artist: string, name: string, uri: string];
  export interface OutputObject {
    artist: string;
    name: string;
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArtistUpdatedEvent {
  export type InputTuple = [artist: AddressLike, name: string, uri: string];
  export type OutputTuple = [artist: string, name: string, uri: string];
  export interface OutputObject {
    artist: string;
    name: string;
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArtistVerifiedEvent {
  export type InputTuple = [artist: AddressLike, verified: boolean];
  export type OutputTuple = [artist: string, verified: boolean];
  export interface OutputObject {
    artist: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArtistProfile extends BaseContract {
  connect(runner?: ContractRunner | null): ArtistProfile;
  waitForDeployment(): Promise<this>;

  interface: ArtistProfileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isArtist: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isVerified: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  profileURI: TypedContractMethod<[addr: AddressLike], [string], "view">;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, boolean] & {
        wallet: string;
        name: string;
        bio: string;
        uri: string;
        exists: boolean;
        verified: boolean;
      }
    ],
    "view"
  >;

  registerArtist: TypedContractMethod<
    [name: string, bio: string, uri: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVerified: TypedContractMethod<
    [artist: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isArtist"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profileURI"
  ): TypedContractMethod<[addr: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, boolean] & {
        wallet: string;
        name: string;
        bio: string;
        uri: string;
        exists: boolean;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerArtist"
  ): TypedContractMethod<
    [name: string, bio: string, uri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerified"
  ): TypedContractMethod<
    [artist: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ArtistRegistered"
  ): TypedContractEvent<
    ArtistRegisteredEvent.InputTuple,
    ArtistRegisteredEvent.OutputTuple,
    ArtistRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ArtistUpdated"
  ): TypedContractEvent<
    ArtistUpdatedEvent.InputTuple,
    ArtistUpdatedEvent.OutputTuple,
    ArtistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ArtistVerified"
  ): TypedContractEvent<
    ArtistVerifiedEvent.InputTuple,
    ArtistVerifiedEvent.OutputTuple,
    ArtistVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ArtistRegistered(address,string,string)": TypedContractEvent<
      ArtistRegisteredEvent.InputTuple,
      ArtistRegisteredEvent.OutputTuple,
      ArtistRegisteredEvent.OutputObject
    >;
    ArtistRegistered: TypedContractEvent<
      ArtistRegisteredEvent.InputTuple,
      ArtistRegisteredEvent.OutputTuple,
      ArtistRegisteredEvent.OutputObject
    >;

    "ArtistUpdated(address,string,string)": TypedContractEvent<
      ArtistUpdatedEvent.InputTuple,
      ArtistUpdatedEvent.OutputTuple,
      ArtistUpdatedEvent.OutputObject
    >;
    ArtistUpdated: TypedContractEvent<
      ArtistUpdatedEvent.InputTuple,
      ArtistUpdatedEvent.OutputTuple,
      ArtistUpdatedEvent.OutputObject
    >;

    "ArtistVerified(address,bool)": TypedContractEvent<
      ArtistVerifiedEvent.InputTuple,
      ArtistVerifiedEvent.OutputTuple,
      ArtistVerifiedEvent.OutputObject
    >;
    ArtistVerified: TypedContractEvent<
      ArtistVerifiedEvent.InputTuple,
      ArtistVerifiedEvent.OutputTuple,
      ArtistVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
