/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as artistVSol from "./artistV.sol";
export type { artistVSol };
import type * as marketSol from "./market.sol";
export type { marketSol };
import type * as nftSol from "./nft.sol";
export type { nftSol };
