/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as artistVSol from "./artistV.sol";
export * as marketSol from "./market.sol";
export * as nftSol from "./nft.sol";
